### ISSUE TITLE
create a script for logging requests from google gemini

### ISSUE THREAD

**Issue by abubakarsohail** [MagnivOrg/prompt-layer-library#119]
The purpose of this task is to create a script for logging requests made via google gemini. This task will include serialization of data to be sent over network.

**Comment by abubakarsohail** [comment]
https://gist.github.com/abubakarsohail/0ece4ed8a1109a17498c9f9adba76a92

**Comment by buckyroberts** [comment]
You need to import `os`

![Image](https://github.com/MagnivOrg/prompt-layer-library/assets/8547538/f9a31ca9-b6e8-496a-b63b-70616a6ef76b)

**Comment by buckyroberts** [comment]
Aside from the comment above everything else looks good. 

![Image](https://github.com/MagnivOrg/prompt-layer-library/assets/8547538/4f3557c9-328e-43fb-ba9b-a878bdd8ebc4)
