### ISSUE TITLE
Feature request: Programatically be able to assign labels

### ISSUE THREAD

**Issue by jalkestrup** [MagnivOrg/prompt-layer-library#130]
Hi!

I am lacking the feature to assign labels when programmatically pushing prompt templates. I would imagine simply adding a parameter called label, passed along when doing the Post request.

When fetching prompt templates I can retrieve a template based on labels, but I am looking for the option to also set them when pushing an updated template back. 

Kind regards,
Jesper

**Comment by Jped** [comment]
This has been added to the rest API, coming soon as arguments for the python and javascript sdk
