### ISSUE TITLE
Update for new anthropic version please

### ISSUE THREAD

**Issue by BedirT** [MagnivOrg/prompt-layer-library#152]
https://github.com/anthropics/anthropic-sdk-python/releases/tag/v0.29.0 for the new claude model

**Comment by abubakarsohail** [comment]
> https://github.com/anthropics/anthropic-sdk-python/releases/tag/v0.29.0 for the new claude model

Hi @BedirT the library should work with the latest version of anthropic SDK. Can you tell us a little bit more about the issue you are facing?

**Comment by abubakarsohail** [comment]
Closing this as the SDK already supports this

**Comment by abubakarsohail** [comment]
I see what the issue is. `anthropic` and `openai` are added as a dependency, which is wrong. Will fix this with a PR soon.
