### ISSUE TITLE
Missing arguments, unable to use with langchain

### ISSUE THREAD

**Issue by aseem2625** [MagnivOrg/prompt-layer-library#17]
OpenAi has configurations as 2nd argument while PromptLayer has just one.

https://github.com/hwchase17/langchainjs/blob/main/langchain/src/llms/openai.ts#L135

https://github.com/hwchase17/langchainjs/blob/main/langchain/src/llms/openai.ts#L400

My main use case is to use for performance analytics, prompt versioning and prompt improving based on user feedback. 

I am using configuration for [other tool](https://js.langchain.com/docs/ecosystem/helicone) in OpenAI call.

**Comment by Jped** [comment]
The LangChain promptlayer TS implementation is a bit behind, we are working to get it up to speed.
