### ISSUE TITLE
Add support for async calls to LangChain LLMs

### ISSUE THREAD

**Issue by creatorrr** [MagnivOrg/prompt-layer-library#2]
See [here](https://langchain.readthedocs.io/en/latest/modules/llms/async_llm.html)

**Comment by Jped** [comment]
@creatorrr  is this something you are currently using on LangChain, or is this just an observation that we don't support this.
Looking for some context to help prioritize this.

**Comment by Jped** [comment]
That is fair. We can hopefully start working on this soon and keep you in the loop. 

If you do have some time yourself it shouldn't be too difficult to make a PR. Basically we would have to define `_agenerate` in our [LangChain OpenAI LLM](https://github.com/MagnivOrg/prompt-layer-library/blob/master/promptlayer/langchain/llms/openai.py) to call [the OpenAI LLM's `_agenerate`](https://github.com/hwchase17/langchain/blob/master/langchain/llms/openai.py#L223) and then pass the data back to our API using `promptlayer_api_request` util function.

**Comment by Jped** [comment]
@creatorrr  What version of langchain are you using? I cant get the example on the link you shared to work.

**Comment by Jped** [comment]
@creatorrr we now support this with the most recent version of promptlayer (0.1.66) https://pypi.org/project/promptlayer/
