### ISSUE TITLE
stream in PromptLayerChatOpenAI

### ISSUE THREAD

**Issue by miguelwon** [MagnivOrg/prompt-layer-library#20]
Hi,
Can we do stream output when using `PromptLayerChatOpenAI`? 
Thanks

**Comment by Jped** [comment]
Hey Miguel, our LangChain integration is still behind on a few things, we are currently finishing up our Langchain TS support and then we can go ahead and add support for streaming. Would you be able to add this feature request [here](https://promptlayer.canny.io/feature-requests)?

**Comment by tecoad** [comment]
Hi @Jped , i see langchain integration still not supporting the messages object, but only string. Which means is very outdated, right?

**Comment by Jped** [comment]
@tecoad are you using Langchain in TS or in Python? In python we do support Message objects, in TypeScript we have a PR open to add support which should be done very soon.

**Comment by Jped** [comment]
Sure, [check out this PR](https://github.com/hwchase17/langchainjs/pull/1274/files/338110c4f8d3cfb8e6e692e8ed39c3e41329f59a..9f8ce23bfbb57508e1368ec852a567af2bbb2074)
