### ISSUE TITLE
finish up async python library stuff

### ISSUE THREAD

**Issue by M-Naveed-Ashraf** [MagnivOrg/prompt-layer-library#208]
Two methods left to be converted as Async

1. `pl_client.run()`
2. `pl_client.templates.publish()` this is blocked due to this [https://github.com/MagnivOrg/prompt-layer-api/pull/2638](https://github.com/MagnivOrg/prompt-layer-api/pull/2638) ([here's the issue](https://linear.app/magniv/issue/ENG-481/fix-bug-causing-duplicate-prompt-templates-with-async-publish-method))

However we already support AsyncOpenai & AsyncAnthropic clients through proxy other than that there's nothing left to be converted as async.

While I was converting all of the methods I found some code duplications in clients and I discussed this with AbuBakar & Bucky and gone through some refactoring to [use mixins](https://github.com/MagnivOrg/prompt-layer-library/pull/211/files#diff-2dbfd5d02315383a8606cb496835d76ed2e5446487b61cd78f4da96d0fffb71a). However there's still need some refactoring in `promptlayer/utils.py`  as it consists of code duplications as well as we're using two different  http client `requests` & `httpx`. which is not an optimal thing we need to use only one and we paused it for next iteration after black friday.

**Comment by M-Naveed-Ashraf** [comment]
Make the following functions asynchronous in python library
1. `pl_client.run` ⌛

**Comment by M-Naveed-Ashraf** [comment]
Make the Library Async thing more robust and unified in sense of code structure

**Comment by MrPupik** [comment]
Will this fix support AsyncOpenai & AsyncAnthropic clients?
