### ISSUE TITLE
Error when retrieving prompt

### ISSUE THREAD

**Issue by bmanturner** [MagnivOrg/prompt-layer-library#25]
`PromptLayer had the following error while getting your prompt: Expecting value: line 1 column 1 (char 0)`

Were there any breaking changes in the recent update? I haven't changed any promptlayer code but my code now fails and I've had to comment out promptlayer calls to get it to work.

**Comment by Jped** [comment]
Can you try again? There might have been a small issue while we were pushing a small update about 5 minutes ago.

**Comment by bmanturner** [comment]
Working now!
