### ISSUE TITLE
how can I get a list of templates in the prompt registry?

### ISSUE THREAD

**Issue by kj-hong-ascentko** [MagnivOrg/prompt-layer-library#28]
It would be nice to have an API to query or retrieve information from the prompt registry😀

**Comment by Jped** [comment]
Hey @kj-hong-ascentko , just so I understand correctly you want an API endpoint that will give you all the prompts in the registry or just a single one? We already have the `/rest/get-prompt-template` that given a prompt template name and version will return the prompt for you.

**Comment by kj-hong-ascentko** [comment]
@Jped 
I want to return all the prompt names stored in the prompt registry or those that meet the specified conditions.
ex) prompts whose prompt names begin with a specific word

**Comment by kj-hong-ascentko** [comment]
@Jped 
Okay, I'll open an issue there as well.

**Comment by Jped** [comment]
http://docs.promptlayer.com/features/prompt-registry#getting-all-prompts
