### ISSUE TITLE
How can I get the meta information of the prompt?

### ISSUE THREAD

**Issue by salmon131** [MagnivOrg/prompt-layer-library#31]
I want to check the meta information of the prompt in get api (for example, the version information of the returned prompt and the creation time, etc.).

**Comment by Jped** [comment]
Are you trying to retrieve all of the metadata for a request given the request id?

**Comment by salmon131** [comment]
What I mean is that I want to check the meta information [when I look up the prompt in the prompt registry](https://docs.promptlayer.com/getting-started/pAYTtfNTUgzx4Y3oVR6CHE/using-our-rest-api/u5Hir2MXYR6qMuCvm876cQ#get-prompt-template), not the meta information about the request.

Currently, I know that the most recent version will be returned when inquiring under the name of prompt. However, it is not possible to determine the version, when the prompt was registered, and so on.
