### ISSUE TITLE
Improve error message

### ISSUE THREAD

**Issue by lfoppiano** [MagnivOrg/prompt-layer-library#42]
I would like to know if there is a way to know what is the root cause of such error: 

```
WARNING: While logging your request PromptLayer had the following error: Expecting value: line 1 column 1 (char 0)
```

It seems a malformed JSON, but without accessing or printing the output (maybe just an error due to a prompt that is too large, or other issue with openai). 

Thank you in advance

**Comment by jzone3** [comment]
Can you please send the request you are trying to log?

**Comment by lfoppiano** [comment]
I'm sorry, I don't have the prompt I was using. I forgot what I was doing last week 😸 
I was calling through langchain.

**Comment by lfoppiano** [comment]
@jzone3 I've got the same now, and the cause is not due to promptlayer. But perhaps you could improve the error messaging, by showing at least the status code and the returned error. 
For example, in my case it's the proxy at my organisation that suddenly blocked promptlayer.

**Comment by lfoppiano** [comment]
@jzone3 I've opened a PR to try to mitigate this issue: https://github.com/MagnivOrg/prompt-layer-library/pull/46
