### ISSUE TITLE
issue with publishing prompt template

### ISSUE THREAD

**Issue by BanaIbrahim** [MagnivOrg/prompt-layer-library#48]
publishing a template is failing with me, I debugged the whole process of creating LangChain messages and all seems right.
Here is the Error:
`Exception: PromptLayer had the following error while publishing your prompt: PromptLayer had the following error while publishing your prompt: [{'loc': ['prompt_template', 'template'], 'msg': 'field required', 'type': 'value_error.missing'}]`

**Comment by abubakarsohail** [comment]
Hi @BanaIbrahim can you share your prompt template here?

**Comment by nkoprowicz3** [comment]
I'm having the same issue. I'm running code that I was able to run with no problems on Monday but now I get this exception. Here's an example

```
template = "Some system template"
system_message_prompt = SystemMessagePromptTemplate.from_template(template)
human_template = "Some human template"
human_message_prompt = HumanMessagePromptTemplate.from_template(human_template)
chat_prompt = ChatPromptTemplate.from_messages([system_message_prompt, human_message_prompt])
promptlayer.prompts.publish('chat_prompt', prompt_template=chat_prompt, tags=['chat'])
```

**Comment by Jped** [comment]
@BanaIbrahim and @nkoprowicz3 please try again

**Comment by BanaIbrahim** [comment]
> @BanaIbrahim and @nkoprowicz3 please try again

Yeah it's working again. Thanks!
