### ISSUE TITLE
Async Streaming yields the complete response after streaming it.

### ISSUE THREAD

**Issue by jxnl** [MagnivOrg/prompt-layer-library#5]
If a stream is supposed to generate "A B C D" as tokens, i expect the yields to be 

```
A 
B
C
D
```

instead i get 
```
A 
B
C
D
A\n\B\nD\C
```

the last yield is the whole result which makes the application double the result.

**Comment by Jped** [comment]
@jxnl good catch, we were doing a shallow instead of deep copy. Should be fixed with version `0.1.71` please open back up if it doesn't.
