### ISSUE TITLE
Anthropic API wrapper issue on count_tokens

### ISSUE THREAD

**Issue by BedirT** [MagnivOrg/prompt-layer-library#60]
Hey,

I realized today that there is an error on the Anthropic wrapper. It assumes the `count_tokens` to be a response call (which it isn't). This results in a dashboard error.

<img width="249" alt="Screenshot 2023-08-15 at 1 31 06 PM" src="https://github.com/MagnivOrg/prompt-layer-library/assets/10860127/0c4b4fb8-3411-4851-b689-b7d25bb69595">
<img width="489" alt="Screenshot 2023-08-15 at 1 30 56 PM" src="https://github.com/MagnivOrg/prompt-layer-library/assets/10860127/703c0f18-56e7-4907-bd4c-84073f47d383">

This also blocks the history view.

**Comment by BedirT** [comment]
Still not fixed

**Comment by Jped** [comment]
@BedirT sorry for the wait. Looking into this now.

**Comment by Jped** [comment]
We decided that this is an issue with our frontend and not our API. Meaning, expected behavior is to send everything that is called using our proxied library to PromptLayer (even though it may not be relevant, but it is hard for us to determine what is and what isnt relevant without having an explicit white list). 

With that we just pushed a quick fix to the dashboard, and will have a better UX for this on the frontend coming soon

**Comment by BedirT** [comment]
I think you should look into it again. The wrapper still looks for the count function and actually makes it extremely heavy. Based on my tests the difference makes the promptlayer unusable with anthropic (since we have to use token counter for the most part)

| API | Time taken (seconds) (100 samples) |
| --- | --- |
| anthropic | 0.00220 |
| promptlayer | 31.58095 |

If you are curious, here is the basic code I used for testing:

```python
# Just Anthropic
anthropic = anthropic.Anthropic(
    api_key=os.environ['ANTHROPIC_API_KEY']
)
some_text = "test text with some words"
# time

start = time.time()
for i in range(int(1e2)):
    anthropic.count_tokens(some_text)
end = time.time()
print("Time taken {:.5f} seconds".format(end-start))
```
```python
# With promptlayer
promptlayer.api_key = os.environ.get("PROMPTLAYER_API_KEY")
anthropic = promptlayer.anthropic
anthropic_api_key = os.environ["ANTHROPIC_API_KEY"]

anthropic = anthropic.Anthropic(
    api_key=os.environ['ANTHROPIC_API_KEY']
)

start = time.time()
for i in range(int(1e2)):
    anthropic.count_tokens(some_text)
end = time.time()
print("Time taken {:.5f} seconds".format(end-start))
```

**Comment by Jped** [comment]
@BedirT the time difference is because we are sending the count_tokens response to our api. I will look into just skipping that function call.

**Comment by Jped** [comment]
@BedirT please upgrade the python library, just pushed a fix
