### ISSUE TITLE
Issue with brackets parsing in system prompt

### ISSUE THREAD

**Issue by BedirT** [MagnivOrg/prompt-layer-library#73]
When I try to use brackets in the system prompt it removes my prompt after saving. There is no error log whatsoever, but I am assuming it is some parsing error. This shouldn't be happening as I want to use some JSON description. Even if the brackets are on different lines this happens. I tried escaping but that didn't work either.

**Comment by abubakarsohail** [comment]
Hi @BedirT can you provide a sample of the data you are trying to send?

**Comment by BedirT** [comment]
Yeah you can just try
```
{
}
```

**Comment by BedirT** [comment]
Or any other json integrated prompt will do the same

**Comment by Jped** [comment]
@BedirT is this happening via the library or the dashboard?

**Comment by BedirT** [comment]
This is on the dashboard.

**Comment by Jped** [comment]
@BedirT we are working on a solution. Can you explain one more time why you want to have empty brackets in the system prompt?

**Comment by BedirT** [comment]
I dont really want empty brackets but that was an example. I have a json output description such as:

"I want you to output in the following format

{
   "key": "value",
   ...
}
"

**Comment by Jped** [comment]
@BedirT thanks for this, we will try to have something by tomorrow

**Comment by Jped** [comment]
Hey @BedirT can you try again? It should be fixed.

**Comment by BedirT** [comment]
Works perfectly now, thanks!
