### ISSUE TITLE
ChatCompletion support request

### ISSUE THREAD

**Issue by lucasgadams** [MagnivOrg/prompt-layer-library#8]
:)

**Comment by okomarov** [comment]
Just emailed you and then found this issue. Would be nice to keep this open or somehow track progress on this item. For reference LangChain supports multiple completions already: https://js.langchain.com/docs/getting-started/guide-chat#multiple-completions

**Comment by Jped** [comment]
@okomarov we do support chat completions, but our prompt registry does not support saving a chat style prompt template. We are waiting for langchain to [implement serialization](https://github.com/hwchase17/langchain/blob/master/langchain/prompts/chat.py#L186) for chat style prompts. They told us they will do it soon, but I will reach back out to figure out what their timeline is.
