### ISSUE TITLE
Importing PromptTemplate from langchain root module is no longer supported

### ISSUE THREAD

**Issue by dmyoung9** [MagnivOrg/prompt-layer-library#82]
This simple warning is being issued by LangChain, starting with version 0.0.32:

```
UserWarning: Importing PromptTemplate from langchain root module is no longer supported.
```

as a result of this PR: https://github.com/langchain-ai/langchain/pull/11047

While not necessarily the end of the world, it should be an easy fix 👌🏼

**Comment by Jped** [comment]
@dmyoung9 thanks for this, i will get to this PR today.
