### ISSUE TITLE
prompts.all() fails silently

### ISSUE THREAD

**Issue by PFacheris** [MagnivOrg/prompt-layer-library#89]
Attempting to list all prompts simply prints 'items' if the API key is not set due to the KeyError.

https://github.com/MagnivOrg/prompt-layer-library/blob/master/promptlayer/prompts/prompts.py#L80-L83

This should likely be raising an exception so that it can be handled by the caller.

**Comment by Jped** [comment]
@PFacheris just fixed it, thanks for pointing this out!
