### ISSUE TITLE
Langchain import

### ISSUE THREAD

**Issue by BedirT** [MagnivOrg/prompt-layer-library#92]
Hey,

I think the library is requiring long-chain imports currently, but it is not stated as a requirement. We are not making use of any langchain properties but even though after promptlayer installation, we need a separate langchain installation.

PS: I get the error on `prompts/prompts.py`

**Comment by BedirT** [comment]
Which is weird cuz i see that langchain is listed in the `toml` file here.

**Comment by Jped** [comment]
Hey @BedirT it is required for some formatting when you do `promptlayer.prompts.get` we are working on a refactor to get rid of that dependancy. It should be out soon.

cc @abubakarsohail

**Comment by Jped** [comment]
This is no longer a requirement when using the updated `promptlayer.templates.get` method
