### ISSUE TITLE
remove langchain and allow users to publish prompt templates of any shape

### ISSUE THREAD

**Issue by abubakarsohail** [MagnivOrg/prompt-layer-library#94]
Remove `langchain` references from the library and allow users to publish prompt templates of any shape. 

Add a warning about the updated shape of prompt template for the users. Add a warning for `prompts.get` as well to let users know about the changes. 

Consult with @Jped about adding a nice type on the library to guide users into using the new shape of prompt template object so that they are only sending a valid object which they can easily edit the on the dashboard as well. 

Try to add some code snippets to showcase how to use the updated object in different workflows like 

- openai
- anthropic
- langchain

Again, make sure to test these changes properly.

**Comment by Jped** [comment]
@abubakarsohail is the adding of helper functions to prepare the template for the different model providers part of this issue or is there another one?

**Comment by abubakarsohail** [comment]
> @abubakarsohail is the adding of helper functions to prepare the template for the different model providers part of this issue or is there another one?

I missed adding that detail here.

**Comment by Jped** [comment]
Amazing thanks.

**Comment by Jped** [comment]
@abubakarsohail this issue will be closed with the new prompt library, can you link that PR here?
